# -*- coding: utf-8 -*-
"""ToyProjectDay13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehODDQ20hlYNXfclEarEVC29NDeXJhTn
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/placement.csv')
df.info()

df.head()

df = df.iloc[:,1:]

df.head()

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c = df['placement'])

X = df.iloc[:,0:2]
X

y = df.iloc[:,-1]
y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_train

X_test = scaler.fit_transform(X_test)

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

y_test

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X_train,y_train.values,clf=clf, legend = 2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))